"""
Django settings for datacenter project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

LINE_CHANNEL_ACCESS_TOKEN = '4mT4bjE6AI04N7rogJNUC2GTggrtMt4/kkqIEWBJcytXdqrJAbg3FrqA6Tm0CaqacIb/UEGD8zjG9drT7PlzqEzW/P5cjfnxe/GwoDEJ26Yy46HZNGE5lHr+YV8bwYvz5Bph+GOXxANSctIuD51gfQdB04t89/1O/w1cDnyilFU=' #在line developer的message api裡
LINE_CHANNEL_SECRET = '1b533df7af30cf5712cb39738ff0afae' #在line developer的basic setting裡
SECRET_KEY = 'Django專案的Secret Key'#此處不需更改


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-80o3)2v4tz(_68jw=a^*zc6eeu^=@4#eg!5#why7jbid09ms&7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mysite',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'datacenter.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'mysite', 'templates')], #加上templates,mysite路徑
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'datacenter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/' #加入static路徑
STATICFILES_DIR = [       
    os.path.join(BASE_DIR, 'static'), #static靜態資料，templates則是用於放模版，也就是寫好的html的網頁
]

IMPORT_EXPORT_USE_TRANSACTIONS = True

MEDIA_URL = '/media/'     #指定媒體文件的 URL 路徑
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
#只要使用者上傳圖片後，Django就會自動建立media資料夾，並且在它底下建立資料模型中所定義的路徑(image/)，來存放圖片

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = ['https://vs-line-bot-25.onrender.com']
