# Generated by Django 5.0.4 on 2024-06-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='description',
            field=models.TextField(default='none', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logmessage',
            name='name',
            field=models.CharField(default='none', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logmessage',
            name='slug',
            field=models.SlugField(default='default_name'),
            preserve_default=False,
        ),
    ]
