# Generated by Django 5.0.4 on 2024-06-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_logmessage_description_logmessage_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='logmessage',
            name='destination',
            field=models.ManyToManyField(related_name='cruise', to='mysite.logmessage'),
        ),
    ]
