# Generated by Django 5.0.4 on 2024-07-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_cruise_logmessage_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=20)),
                ('cGender', models.CharField(default='M', max_length=2)),
                ('cEmail', models.EmailField(blank=True, default='', max_length=100)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Cruise',
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
    ]
