# Generated by Django 5.0.4 on 2024-07-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_teacher_delete_cruise_delete_logmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='ccourse',
            field=models.CharField(default='default_course', max_length=50),
        ),
    ]
