# Generated by Django 5.0.4 on 2024-07-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_albummodel_photomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='photomodel',
            name='palbum',
        ),
        migrations.DeleteModel(
            name='AlbumModel',
        ),
        migrations.DeleteModel(
            name='PhotoModel',
        ),
    ]
