# Generated by Django 5.0.4 on 2024-07-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_photo_remove_photomodel_palbum_delete_albummodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
    ]
