# Generated by Django 5.0.4 on 2024-07-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_remove_photo_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cgrade',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='csemmester',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
