# Generated by Django 5.0.4 on 2024-07-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_remove_photo_title_photo_upload_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='upload_data',
            new_name='upload_date',
        ),
    ]
