# Generated by Django 5.0.4 on 2024-08-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncourse', models.CharField(default='default_course', max_length=50)),
                ('nbook', models.CharField(default='default_book', max_length=50)),
                ('nschedule', models.TextField(max_length=2000)),
            ],
        ),
    ]
