# Generated by Django 5.0.4 on 2024-08-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='ngrade',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
