# Generated by Django 5.0.4 on 2024-08-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_syllabus_ngrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccourse', models.CharField(default='default_course', max_length=50)),
                ('csemester', models.CharField(max_length=50)),
                ('cgrade', models.CharField(default=0, max_length=50)),
                ('cName', models.CharField(max_length=20)),
                ('cGender', models.CharField(default='M', max_length=4)),
                ('cEmail', models.EmailField(blank=True, default='', max_length=100)),
                ('cdescription', models.TextField(max_length=2000)),
            ],
        ),
    ]
