# Generated by Django 5.0.4 on 2024-08-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_teacher2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher2',
            old_name='cEmail',
            new_name='aEmail',
        ),
        migrations.RenameField(
            model_name='teacher2',
            old_name='cGender',
            new_name='aGender',
        ),
        migrations.RenameField(
            model_name='teacher2',
            old_name='cName',
            new_name='aName',
        ),
        migrations.RenameField(
            model_name='teacher2',
            old_name='ccourse',
            new_name='acourse',
        ),
        migrations.RenameField(
            model_name='teacher2',
            old_name='cdescription',
            new_name='adescription',
        ),
        migrations.RenameField(
            model_name='teacher2',
            old_name='cgrade',
            new_name='agrade',
        ),
        migrations.RenameField(
            model_name='teacher2',
            old_name='csemester',
            new_name='asemester',
        ),
    ]
