# Generated by Django 5.0.4 on 2024-08-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_rename_cemail_teacher2_aemail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teacher2',
            new_name='teacher_second',
        ),
    ]
