# Generated by Django 5.0.4 on 2024-08-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_rename_teacher2_teacher_second'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_third',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acourse', models.CharField(default='default_course', max_length=50)),
                ('asemester', models.CharField(max_length=50)),
                ('agrade', models.CharField(default=0, max_length=50)),
                ('aName', models.CharField(max_length=20)),
                ('aGender', models.CharField(default='M', max_length=4)),
                ('aEmail', models.EmailField(blank=True, default='', max_length=100)),
                ('adescription', models.TextField(max_length=2000)),
            ],
        ),
    ]
