# Generated by Django 5.0.4 on 2024-08-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_teacher_eighth_teacher_fifth_teacher_fourth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='syllabus_eighth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncourse', models.CharField(default='default_course', max_length=50)),
                ('nbook', models.CharField(default='default_book', max_length=50)),
                ('nschedule', models.TextField(max_length=2000)),
                ('ngrade', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='syllabus_fifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncourse', models.CharField(default='default_course', max_length=50)),
                ('nbook', models.CharField(default='default_book', max_length=50)),
                ('nschedule', models.TextField(max_length=2000)),
                ('ngrade', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='syllabus_fourth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncourse', models.CharField(default='default_course', max_length=50)),
                ('nbook', models.CharField(default='default_book', max_length=50)),
                ('nschedule', models.TextField(max_length=2000)),
                ('ngrade', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='syllabus_sencond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncourse', models.CharField(default='default_course', max_length=50)),
                ('nbook', models.CharField(default='default_book', max_length=50)),
                ('nschedule', models.TextField(max_length=2000)),
                ('ngrade', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='syllabus_seventh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncourse', models.CharField(default='default_course', max_length=50)),
                ('nbook', models.CharField(default='default_book', max_length=50)),
                ('nschedule', models.TextField(max_length=2000)),
                ('ngrade', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='syllabus_sixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncourse', models.CharField(default='default_course', max_length=50)),
                ('nbook', models.CharField(default='default_book', max_length=50)),
                ('nschedule', models.TextField(max_length=2000)),
                ('ngrade', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='syllabus_third',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncourse', models.CharField(default='default_course', max_length=50)),
                ('nbook', models.CharField(default='default_book', max_length=50)),
                ('nschedule', models.TextField(max_length=2000)),
                ('ngrade', models.TextField(max_length=2000)),
            ],
        ),
    ]
