# Generated by Django 5.0.4 on 2024-08-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_syllabus_eighth_syllabus_fifth_syllabus_fourth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=10)),
                ('strengths', models.TextField(max_length=2000)),
                ('tel', models.CharField(max_length=100)),
                ('mail', models.EmailField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
