# Generated by Django 5.0.4 on 2024-08-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_teacher_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_sixth',
            name='aName',
            field=models.CharField(max_length=100),
        ),
    ]
