# Generated by Django 5.0.4 on 2024-08-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_alter_teacher_sixth_aname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_seventh',
            name='aName',
            field=models.CharField(max_length=100),
        ),
    ]
