# Generated by Django 5.0.4 on 2024-09-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_alter_teacher_seventh_aname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teacher_info',
            new_name='teacher_data',
        ),
    ]
