# Generated by Django 5.0.4 on 2024-09-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_rename_teacher_info_teacher_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='nsemester',
            field=models.CharField(default=113, max_length=50),
            preserve_default=False,
        ),
    ]
