# Generated by Django 5.0.4 on 2024-09-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_syllabus_nsemester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='syllabus_eighth',
        ),
        migrations.DeleteModel(
            name='syllabus_fifth',
        ),
        migrations.DeleteModel(
            name='syllabus_fourth',
        ),
        migrations.DeleteModel(
            name='syllabus_sencond',
        ),
        migrations.DeleteModel(
            name='syllabus_seventh',
        ),
        migrations.DeleteModel(
            name='syllabus_sixth',
        ),
        migrations.DeleteModel(
            name='syllabus_third',
        ),
    ]
