# Generated by Django 5.0.4 on 2024-09-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_delete_syllabus_eighth_delete_syllabus_fifth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
