# Generated by Django 5.0.4 on 2024-09-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0030_syllabus_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='name',
            new_name='nname',
        ),
    ]
