# Generated by Django 5.0.4 on 2024-09-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0031_rename_name_syllabus_nname'),
    ]

    operations = [
        migrations.CreateModel(
            name='syllabus_second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncourse', models.CharField(default='default_course', max_length=50)),
                ('nname', models.CharField(max_length=50)),
                ('nsemester', models.CharField(max_length=50)),
                ('nbook', models.CharField(default='default_book', max_length=50)),
                ('nschedule', models.TextField(max_length=2000)),
                ('ngrade', models.TextField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
