# Generated by Django 5.0.4 on 2024-09-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0033_userrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRating',
            new_name='rating',
        ),
    ]
