# Generated by Django 5.0.4 on 2024-09-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0034_rename_userrating_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rating',
            new_name='user_rating',
        ),
    ]
