# Generated by Django 5.0.4 on 2024-09-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0035_rename_rating_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_rating',
            name='user_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
