# Generated by Django 5.0.4 on 2024-11-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0036_user_rating_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_data',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
